dist: trusty
sudo: required
language: c++

os:
  - linux
  - osx

before_script: 
  - apt-get install ocamlfind opam -y
  - opam init -y
  - eval $(opam config env)
  - opam install cryptokit yojson
  - ./interpreter/meta/travis/install-ocaml.sh

script: 
  - ./interpreter/meta/travis/build-test.sh
